# Generated by Django 5.1.1 on 2024-09-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0039_remove_historial_fdb_fk_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animalesdb',
            name='desc',
        ),
        migrations.AlterField(
            model_name='animalesdb',
            name='edad',
            field=models.DateField(verbose_name='Fecha de nacimiento aprox.'),
        ),
    ]
