# Generated by Django 5.1.1 on 2024-10-06 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0041_alter_tamañodb_options_remove_animalesdb_obs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopcionesdb',
            name='Animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP.animalesdb'),
        ),
        migrations.AddField(
            model_name='animalesdb',
            name='fk_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='CI_cuidador'),
        ),
        migrations.DeleteModel(
            name='Resguardodb',
        ),
    ]
